import type { NextPage } from "next";
import Head from "next/head";
import { Overview } from "../component/Templates/Overview";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>EC-site</title>
        {/* TODO: metaの中身とは */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Overview />
    </div>
  );
};

export default Home;
